### ISSUE TITLE
同步下的报错 发生异常了：Expected HTTP 101 response but was '401 Unauthorized'

### ISSUE THREAD

**Issue by BIBIYES** [briqt/xunfei-spark4j#12]
在使用同步调用下发生了一下报错
java.net.ProtocolException: Expected HTTP 101 response but was '401 Unauthorized'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) [okhttp-4.9.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_301]

发生异常了：Expected HTTP 101 response but was '401 Unauthorized'
运行测试类也出现了同样的错误
![QQ截图20240424115150](https://github.com/briqt/xunfei-spark4j/assets/92933688/3a4e10a7-400d-4a49-8499-af2a271ed392)
![Uploading QQ截图20240424115223.png…]()

**Comment by briqt** [comment]
检查一下 key 和密钥，你应该是写反了

**Comment by BIBIYES** [comment]
**还真的是写反了**，谢谢作者
