### ISSUE TITLE
输入违规内容以后报错 但是不知道在哪里抓取报错

### ISSUE THREAD

**Issue by xumouren1234** [briqt/xunfei-spark4j#3]
Exception in thread "OkHttp Dispatcher" io.github.briqt.spark4j.exception.SparkException: 讯飞星火api连接异常：输入内容审核不通过，涉嫌违规，请重新调整输入内容
	at io.github.briqt.spark4j.listener.SparkBaseListener.onFailure(SparkBaseListener.java:110)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:197)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.github.briqt.spark4j.exception.SparkException: 输入内容审核不通过，涉嫌违规，请重新调整输入内容
	at io.github.briqt.spark4j.exception.SparkException.bizFailed(SparkException.java:33)
	at io.github.briqt.spark4j.listener.SparkBaseListener.onMessage(SparkBaseListener.java:84)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)

**Comment by xumouren1234** [comment]
public  String privateChat(String userid,String massage) {

       



        // 消息列表，可以在此列表添加历史对话记录


       /* messages.add(SparkMessage.userContent("请你扮演我的语文老师李老师，问我讲解问题问题，希望你可以保证知识准确，逻辑严谨。"));
        messages.add(SparkMessage.assistantContent("好的，这位同学，有什么问题需要李老师为你解答吗？"));*/
        messages.add(SparkMessage.userContent(massage));


// 构造请求
        SparkRequest sparkRequest = SparkRequest.builder()
                .chatId(userid)
// 消息列表
                .messages(messages)
// 模型回答的tokens的最大长度,非必传,取值为[1,4096],默认为2048
                .maxTokens(2048)
// 核采样阈值。用于决定结果随机性,取值越高随机性越强即相同的问题得到的不同答案的可能性越高 非必传,取值为[0,1],默认为0.5
                .temperature(0.5)
// 指定请求版本，默认使用最新2.0版本
                .apiVersion(SparkApiVersion.V1_5)
                .build();

// 同步调用
        SparkSyncChatResponse chatResponse=sparkClient.chatSync(sparkRequest);
        SparkTextUsage textUsage=chatResponse.getTextUsage();

        String content = chatResponse.getContent();
        System.out.println("\n回答："+chatResponse.getContent());
        System.out.println("\n提问tokens："+textUsage.getPromptTokens()
                +"，回答tokens："+textUsage.getCompletionTokens()
                +"，总消耗tokens："+textUsage.getTotalTokens());


        return content;
    }

**Comment by briqt** [comment]
如果是同步调用，目前只能手动捕获异常再处理：
``` 
// 同步调用
SparkSyncChatResponse chatResponse;
try {
    chatResponse = sparkClient.chatSync(sparkRequest);
} catch (SparkException e) {
    System.out.println("发生异常了：" + e.getMessage());
    return;
}
System.out.println("\n回答：" + chatResponse.getContent());
```
如果是流式调用，重写SparkBaseListener的onFailure方法即可：
```
// 使用默认的控制台监听器，流式调用；
// 实际使用时请继承SparkBaseListener自定义监听器实现
sparkClient.chatStream(sparkRequest, new SparkConsoleListener() {
    @Override
    public void onFailure(@NotNull WebSocket webSocket, @NotNull Throwable t, Response response) {
        System.out.println("发生异常了：" + t.getMessage());
    }
});
```
