### ISSUE TITLE
为什么输出内容敏感抛异常？

### ISSUE THREAD

**Issue by Ewannai** [briqt/xunfei-spark4j#7]
io.github.briqt.spark4j.exception.SparkException: 输出内容涉及敏感信息，审核不通过，后续结果无法展示给用户
	at io.github.briqt.spark4j.exception.SparkException.bizFailed(SparkException.java:33) ~[xunfei-spark4j-1.1.2.jar:na]
	at io.github.briqt.spark4j.listener.SparkBaseListener.onMessage(SparkBaseListener.java:101) ~[xunfei-spark4j-1.1.2.jar:na]
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) [okhttp-4.9.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_381]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_381]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_381]

发生异常了：输出内容涉及敏感信息，审核不通过，后续结果无法展示给用户
2023-12-22 14:28:43.887 ERROR 3940 --- [0.0-2913-exec-2] c.e.bi.exception.GlobalExceptionHandler  : RuntimeException

在图形界面都能输出该问题的答案，这个里面为啥不行喃

**Comment by briqt** [comment]
// 业务状态判断
        Integer code = header.getCode();
        if (0 != code) {
            webSocket.close(1000, "");
            throw SparkException.bizFailed(code);
        }

![图片](https://github.com/briqt/xunfei-spark4j/assets/131652747/aa8c8a6d-bafa-45b5-8011-247aa691d6c8)

**Comment by briqt** [comment]
只能猜测api的审核相比网页版的服务审核更严格

**Comment by Ewannai** [comment]
好的，感谢，已经解决了
